### ISSUE TITLE
Scanning only on channel 39?

### ISSUE THREAD

**Issue by alessandro-montanari** [NordicSemiconductor/nRF51-multi-role-conn-observer-advertiser#10]
Hi,
is the scanner scanning only on channel 39 or am I missing something?
I was looking at the file ll_scan.c and radio_init() is called only once with the channel number 39.
Does that mean that only that channel is scanned or all of three (37, 38 and 39)?

Thank you.

**Comment by pratyushd** [comment]
Please post your question on the our DevZone, where there such questions do get answered more promptly.

**Comment by daviddedwin** [comment]
You are correct, however you can rotate the scanner slowly to different channels, for example you can scan on 37 for 1 second, 38 on 1 second and then move to 39 for 1 second and repeat. The frequency can be added to the interface function. Alternatively you can switch the channel for each scan interval within the scanner function (no interface changes).

**Comment by alessandro-montanari** [comment]
Thanks daviddedwin!
I have made a pull request with the small change.
