### ISSUE TITLE
is it possible to add support for nrf52 series

### ISSUE THREAD

**Issue by jasonbu** [NordicSemiconductor/nRF51-multi-role-conn-observer-advertiser#26]
excited to find this, and now trying to remap it to s132, it it possible to add a officail support for nrf52 series?

**Comment by alessandro-montanari** [comment]
With s132 on nrf52 you can already have multi roles. Look at the ble_central_and_peripheral examples in the SDK. I took inspiration from the ble_app_hrs_rscs_relay example to scan and advertise concurrently.

**Comment by jasonbu** [comment]
@alessandro-montanari em.. so the multi roles advertise can also send a advertise without the random 0-10ms?  we wanna to do the time-sync with advertisement

**Comment by alessandro-montanari** [comment]
@jasonbu no, the delay is there. I see your point.

**Comment by jasonbu** [comment]
@alessandro-montanari  so it's possible to add this feature?

**Comment by alessandro-montanari** [comment]
@jasonbu I guess it's possible because you still have access to the radio interface directly, without the Softdevice

**Comment by jasonbu** [comment]
@alessandro-montanari  I tried using nRF5_SDK_11.0.0_89a8197\examples\ble_peripheral\experimental_ble_app_multiactivity_beacon\hrs_advertiser this sample to nRF52 and it can be work allright now. but I found questions about the accuracy of the request latency. and trying to debug with it.

**Comment by alessandro-montanari** [comment]
@jasonbu I'm sorry but I'm not a developer of this library, I just used in the past with SDK v6 but I don't really know how it works internally. If you are more specific with your problem I'm sure there will be people able to help. Have you also tried on devzone.nordicsemi.com?

**Comment by jasonbu** [comment]
@alessandro-montanari  I think this issue can be closed now, time accuracy is caused by HFCLKSRC, using RC got 3 thousandths mistake, using XTAL got fixed. it's all works now

**Comment by alessandro-montanari** [comment]
@jasonbu that's good. Just for curiosity can you explain what you were trying to do? I am interested in time-sync stuff :)

**Comment by jasonbu** [comment]
@alessandro-montanari  i think it's not very difficult, put the local timestamp on the adv payload, and remove the random delay. we are trying to do this, and test if it is a good solution.

**Comment by jasonbu** [comment]
ver similar with https://github.com/nordic-auko/nRF5-ble-timesync-demo 
but not special RX within the HOST
