### ISSUE TITLE
periph_ppi_clear(...) clears all bits in NRF_PPI->CHEN

### ISSUE THREAD

**Issue by agren** [NordicSemiconductor/nRF51-multi-role-conn-observer-advertiser#4]
I believe line 211 https://github.com/NordicSemiconductor/nRF51-multi-role-conn-observer-advertiser/blob/dbfe605d26c17b28a859504d878b7b68735decdd/btle_hci/advertiser/ts_peripheral.c#L211 is incorrect.
`NRF_PPI->CHENCLR |= (1 << ppi_ch);` will cause all bits in `NRF_PPI->CHEN` to be cleared. It should be changed to `NRF_PPI->CHENCLR = (1 << ppi_ch);` to work as desired.

The same goes for periph_ppi_set(...)

**Comment by mlshon** [comment]
I'm trying to compile this in Keil, but it gives me an error that boards.h is not found.

I believe this is because I don't quite know what you mean by copying the folders into the s110 folder bcause I don't know where the folder is located
