### ISSUE TITLE
missing boards.h

### ISSUE THREAD

**Issue by mlshon** [NordicSemiconductor/nRF51-multi-role-conn-observer-advertiser#7]
I'm trying to compile this in Keil, but it gives me an error that boards.h is not found.

I believe this is because I don't quite know what you mean by copying the folders into the s110 folder bcause I don't know where the folder is located

**Comment by trond-snekvik** [comment]
Hi!
In addition to the SD110 7.x, This project requires nRF51 SDK 6.x, available at www.nordicsemi.com. The dependencies, like boards.h is available in the SDK (under `/nRF51822/Include/*`), and must be included in the "Include paths" list in Target options in Keil. The folder is included by default, but you might have a different folder structure, and have to change the path. In addition, the files under the `core` and `lib` file groups in Keil might appear as missing. These are part of the SDK as well, and you have to change the path to these files to fit your SDK location. They are found under `/nRF51822/Source/*` and its subfolders in the SDK. Hope this helps.

**Comment by trond-snekvik** [comment]
Since @mlshon had no further comments on this issue, I'm going to assume that the toolchain setup was the problem, and close the issue. Please reopen it if there are any further problems with the toolchain.
