### ISSUE TITLE
Unable to change scan response flag

### ISSUE THREAD

**Issue by collinmast** [NordicSemiconductor/nRF51-multi-role-conn-observer-advertiser#9]
The flag:

#define TS_SEND_SCAN_RSP (1)

in the ts_controller.c file for the advertiser cannot be set to 0. All advertisements, including non-connectable, are sent with a scan response

**Comment by trond-snekvik** [comment]
This issue is fixed in the newest commit. Note that when setting the flag to zero, the advertisement type is forced to ADV_INT_NONCONN, disregarding whatever is provided in the setup parameters.
